/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KRating {
    /**
    * The amount of stars
    */
    'maxValue': number;
    /**
    * The current rating of the stars
    */
    'value': number;
  }
}

declare global {


  interface HTMLKRatingElement extends Components.KRating, HTMLStencilElement {}
  var HTMLKRatingElement: {
    prototype: HTMLKRatingElement;
    new (): HTMLKRatingElement;
  };
  interface HTMLElementTagNameMap {
    'k-rating': HTMLKRatingElement;
  }
}

declare namespace LocalJSX {
  interface KRating {
    /**
    * The amount of stars
    */
    'maxValue'?: number;
    'onRatingUpdated'?: (event: CustomEvent<any>) => void;
    /**
    * The current rating of the stars
    */
    'value'?: number;
  }

  interface IntrinsicElements {
    'k-rating': KRating;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'k-rating': LocalJSX.KRating & JSXBase.HTMLAttributes<HTMLKRatingElement>;
    }
  }
}


